# rebased/repackaged base image that only updates existing packages
FROM mbentley/buildkit-test:base-alpine
LABEL maintainer="Matt Bentley <mbentley@mbentley.net>"

RUN apk --no-cache add curl

ENTRYPOINT ["curl"]
CMD ["--help"]
